---
title: "data!"
author: "Naomi Liftman"
format: pdf
editor: visual
---

# Packages

```{r warning = FALSE, error = FALSE, message = FALSE}
library(incidentally)
library(backbone)
library(smnet)
library(igraph)
library(tidyverse)
library(rio)
library(tidyr)
```

# Scott Code for Cosponsorship of 117th SENATE

```{r warning = FALSE, message = FALSE, error = FALSE}
#pull the 117 senators connections 
B_117_senate <- incidence.from.congress(session = 117, types = c("s", "sres", "sjres", "sconres"), areas = c("All"), format = "igraph")

network_117_senate <- sdsm(B_117_senate, alpha = 0.01, narrative = TRUE)

## Creates matrix object (note adjacency matrix)
el_mat_117_senate <- as_edgelist(network_117_senate)

### creates data frame object
el_117_senate <- as.data.frame(as_edgelist(network_117_senate))
```

# Mutating Cosponsorship of 117th SENATE

```{r}
#remove the senator title from both columns
el_117_senate$V1 <- sub("Sen. ", "", el_117_senate$V1)
el_117_senate$V2 <- sub("Sen. ", "", el_117_senate$V2)

#remove everything after the [
el_117_senate$V1 <- gsub("\\[.*","", el_117_senate$V1)
el_117_senate$V2 <- gsub("\\[.*","", el_117_senate$V2)

#add new columns with the first and last names
el_117_senate$v1_first <- gsub(".*\\, ", "", el_117_senate$V1)   
el_117_senate$v1_last <- gsub("\\,.*","", el_117_senate$V1)
el_117_senate$v2_first <- gsub(".*\\, ", "", el_117_senate$V2)   
el_117_senate$v2_last <- gsub("\\,.*","", el_117_senate$V2) 

#adding them together!
edge_117_senate = el_117_senate %>% 
  unite(v1_full, c(v1_first, v1_last), sep = "", remove = FALSE) %>% 
  unite(v2_full, c(v2_first, v2_last), sep = "", remove = FALSE) %>% 
  select(v1_full, v2_full)
```

# Scott Code for Cosponsorship in 117th HOUSE

```{r warning = FALSE, message = FALSE, error = FALSE}
#pull the 117 senators connections 
B_117_house <- incidence.from.congress(session = 117, types = c("hr", "hres", "hjres", "hconres"), areas = c("All"), format = "igraph")

#this is taking forever to run, not sure why, will check out later
network_117_house <- sdsm(B_117_house, alpha = 0.01, narrative = TRUE)

## Creates matrix object (note adjacency matrix)
el_mat_117_house <- as_edgelist(network_117_house)

### creates data frame object
el_117_house <- as.data.frame(as_edgelist(network_117_house))
```

# Mutating Cosponsorship of 117th HOUSE

```{r}
#remove the house title from both columns
el_117_house$V1 <- sub("Rep. ", "", el_117_house$V1)
el_117_house$V2 <- sub("Rep. ", "", el_117_house$V2)

#remove everything after the [
el_117_house$V1 <- gsub("\\[.*","", el_117_house$V1)
el_117_house$V2 <- gsub("\\[.*","", el_117_house$V2)

#add new columns with the first and last names
el_117_house$v1_first <- gsub(".*\\, ", "", el_117_house$V1)   
el_117_house$v1_last <- gsub("\\,.*","", el_117_house$V1)
el_117_house$v2_first <- gsub(".*\\, ", "", el_117_house$V2)   
el_117_house$v2_last <- gsub("\\,.*","", el_117_house$V2) 

#adding them together!
edge_117_house = el_117_house %>% 
  unite(v1_full, c(v1_first, v1_last), sep = "", remove = FALSE) %>% 
  unite(v2_full, c(v2_first, v2_last), sep = "", remove = FALSE) %>% 
  select(v1_full, v2_full)
```

# MAKING THE FULL EDGE LIST 117th! 

```{r}
#full 117th dataframe
full_117_edge <- rbind(edge_117_house, edge_117_senate)

#renaming to get in correct scheme
full_117_edge <- full_117_edge %>% 
  rename("member_i" = 1,
         "member_j" = 2)
```

# RELIGION FOR 117th

```{r}
#importing the df 
religion_117 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/117congress.xlsx")

#rename the last five names
relig_117 <- religion_117 %>% 
    rename_with(~ tolower(gsub(".", "", .x, fixed = TRUE))) %>%
  rename("type" = 2) %>% 
  rename("name" = 3) %>% 
  rename("party" = 4 ) %>% 
  rename("cont" = 5) %>% 
  rename("religion" = 6)

#rename the state
names(relig_117)[1] = "state"  

#remove the first row
relig_117 <- relig_117[-c(1:1), ]

#only want their name and religion
relig_117 <- relig_117 %>% 
  select("name", "religion")
```

# Merging the 117th full with the religion!!

```{r}
#now we have something that has the first senators religion
t_117_first <- full_join(relig_117, full_117_edge, by = c("name" = "member_i")) 

#rename so we have a name i and a religion i 
#and only select the i's
t_117_first <- t_117_first %>% 
  rename("religion_i" = "religion",
         "member_i" = "name") %>% 
  select("member_i", "religion_i")

#now we have something that has the second senators religion
t_117_second <- full_join(relig_117, full_117_edge, by = c("name" = "member_j"))

#now we have the name j and religion j 
#and only select the js
t_117_second <- t_117_second %>% 
  rename("religion_j" = "religion",
         "member_j" = "name") %>% 
  select("member_j", "religion_j")

#now we just need them all together!!!
all_117 <- cbind(t_117_first, t_117_second)

#need to make the NAs of the religions but we dont want NAs of the ties
#there were 37662 ties before running this
#THEY are the same!! this is slay
#this is just a gut check we did it correctly
all_117[!is.na(all_117$member_i),]
all_117[!is.na(all_117$member_j),]

#now we want to make all the NAs be "Don't know/refused"
#for i
all_117$religion_i <- all_117$religion_i %>%  
  replace_na("Don't know/refused")

#for j
all_117$religion_j <- all_117$religion_j %>%  
  replace_na("Don't know/refused")
#YAYAYYAYAYAY

#now we want to assign a value to if they have the same religion!
DF$score_young <- ifelse(DF$Age <= 16, DF$Score, NA)

#create similarity score!! yay!!
all_117$similarity<- ifelse(all_117$religion_i == all_117$religion_j, 1, 0)

```









# Scott Code for Cosponsorship of 112th SENATE

```{r warning = FALSE, message = FALSE, error = FALSE}
#pull the 117 congress connections 
B_112_senate <- incidence.from.congress(session = 112, types = c("s", "sres", "sjres", "sconres"), areas = c("All"), format = "igraph")

network_112_senate <- sdsm(B_112_senate, alpha = 0.01, narrative = TRUE)

## Creates matrix object (note adjacency matrix)
el_mat_112_senate <- as_edgelist(network_112_senate)

### creates data frame object
el_112_senate <- as.data.frame(as_edgelist(network_112_senate))
```

# Mutating Cosponsorship of 112th SENATE

```{r}
#remove the senator title from both columns
el_112_senate$V1 <- sub("Sen. ", "", el_112_senate$V1)
el_112_senate$V2 <- sub("Sen. ", "", el_112_senate$V2)

#remove everything after the [
el_112_senate$V1 <- gsub("\\[.*","", el_112_senate$V1)
el_112_senate$V2 <- gsub("\\[.*","", el_112_senate$V2)

#add new columns with the first and last names
el_112_senate$v1_first <- gsub(".*\\, ", "", el_112_senate$V1)   
el_112_senate$v1_last <- gsub("\\,.*","", el_112_senate$V1)
el_112_senate$v2_first <- gsub(".*\\, ", "", el_112_senate$V2)   
el_112_senate$v2_last <- gsub("\\,.*","", el_112_senate$V1) 

#adding them together!
edge_112_senate = el_112_senate %>% 
  unite(v1_full, c(v1_first, v1_last), sep = "", remove = FALSE) %>% 
  unite(v2_full, c(v2_first, v2_last), sep = "", remove = FALSE) %>% 
  select(v1_full, v2_full)
```

# Religion Data 112th

```{r}
#importing the df 
religion_112 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/112congress.xlsx") 

#rename the last five names
relig_112 <- religion_112 %>% 
  rename_with(~ tolower(gsub(".", "", .x, fixed = TRUE))) %>% 
  rename("member_name" = 2) %>% 
  rename("religious_affiliation" = 4 ) %>% 
  select("member_name", "religious_affiliation")
```

