---
title: "DW-NOMINATE scores"
author: "Naomi Liftman"
date: "2023-04-21"
output: pdf_document
---
# Load Pacakges
```{r warning = FALSE, error = FALSE, message = FALSE}
library(tidyverse)
library(rio)
library(stringi)                               
```

# 117th 
```{r}
#import the data
dw_117 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/HS117_members.csv")

#select only the ones we want
dw_117 <- dw_117 %>% 
  select(chamber, icpsr, state_abbrev, party_code, bioname, nominate_dim1, )

#remove presidents 
dw_117 <- dw_117[dw_117$chamber != "President", ] 
```

# God so much mutating and fixing the names
```{r}
#making a dataset to fuck around with 
dw_117_mutating <- dw_117

#removing all the ending intials 
dw_117_mutating$bioname <- gsub("(.*)\\s+[A-Z]\\.?$", "\\1", dw_117_mutating$bioname)

#making it all lower case
dw_117_mutating$bioname <- tolower(dw_117_mutating$bioname)

#add new columns with the first and last names
dw_117_mutating$firstname <- gsub(".*\\, ", "", dw_117_mutating$bioname)   
dw_117_mutating$lastname <- gsub("\\,.*","", dw_117_mutating$bioname)

#now making the names caps of first name and last
dw_117_mutating$firstname <- stri_trans_totitle(dw_117_mutating$firstname) 
dw_117_mutating$lastname <- stri_trans_totitle(dw_117_mutating$lastname)                      

#combining them to get their full names!
full_117_names = dw_117_mutating %>% 
  unite(name, c(firstname, lastname), sep = " ", remove = FALSE) %>% 
  select(chamber:name, -bioname)

```

# Religion 117th
```{r}
#doing this so that we can have the correct numbers and they are all the same
#there are 531
#importing the df 
religion_117 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/117congress.xlsx")

#rename the last five names
relig_117 <- religion_117 %>% 
    rename_with(~ tolower(gsub(".", "", .x, fixed = TRUE))) %>%
  rename("type" = 2) %>% 
  rename("name" = 3) %>% 
  rename("party" = 4 ) %>% 
  rename("cont" = 5) %>% 
  rename("religion" = 6)

#remove first row
relig_117 <- relig_117[-c(1:1), ]

#only want name and religion
relig_117 <- relig_117 %>% 
  select("name", "religion")

#creating a new 117
rel_117 <- relig_117 %>% 
  drop_na(name)

#fix all protestant:
rel_117$fix_relig <- ifelse(rel_117$religion == 'Adventist', 'Protestant', rel_117$religion)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Baptist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Congregationalist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Episcopalian', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Lutheran', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Methodist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Pentecostal', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Pietist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Presbyterian', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Protestant unspecified', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Reformed', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Restorationist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Unitarian Universalist', 'Protestant', rel_117$fix_relig)

#fix all general catholic
rel_117$fix_relig <- ifelse(rel_117$religion == 'Orthodox', 'Catholic', rel_117$fix_relig)

#fixing all other
rel_117$fix_relig <- ifelse(rel_117$religion == 'Unaffiliated', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Buddhist', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Hindu', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Mormon', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Muslim', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Nondenominational', 'Other', rel_117$fix_relig)

#replacing all of the NAs with Unknown along with the dont know
rel_117$fix_relig <- ifelse(rel_117$religion == 'Don\'t know/refused', 'Unknown', rel_117$fix_relig)
rel_117$fix_relig <- rel_117$fix_relig %>% replace_na('Unknown')


rel_117 <- rel_117 %>% 
  select("name", "fix_relig") %>% 
  drop_na("name")
```

# Fixing the names that didnt merge correctly
```{r}
full_117_names[full_117_names == "Iii Manchin"] <- "Joe Manchin III"
full_117_names[full_117_names == "Donald Edwin Young"] <- "Don Young"
full_117_names[full_117_names == "Daniel Scott Sullivan"] <- "Dan Sullivan"
full_117_names[full_117_names == "Mike Dennis Rogers"] <- "Mike D. Rogers"
full_117_names[full_117_names == "Robert Aderholt"] <- "Robert B. Aderholt"
full_117_names[full_117_names == "Gary James Palmer"] <- "Gary Palmer"
full_117_names[full_117_names == "Terri Sewell"] <- "Terri A. Sewell"
full_117_names[full_117_names == "Richard Shelby"] <- "Richard C. Shelby"
full_117_names[full_117_names == "Thomas Hawley (Tommy) Tuberville"] <- "Tommy Tuberville"
full_117_names[full_117_names == "Bruce Eugene Westerman"] <- "Bruce Westerman"
full_117_names[full_117_names == "Thomas O'halleran"] <- "Tom O'halleran"
full_117_names[full_117_names == "Raúl Grijalva"] <- "Raul M. Grijalva"
full_117_names[full_117_names == "Andrew Biggs"] <- "Andy Biggs"
full_117_names[full_117_names == "Mark Edward Kelly"] <- "Mark Kelly"
full_117_names[full_117_names == "Doug Lamalfa"] <- "Doug LaMalfa"
full_117_names[full_117_names == "Tom Mcclintock"] <- "Tom McClintock"
full_117_names[full_117_names == "Michael Thompson"] <- "Mike Thompson"
full_117_names[full_117_names == "Jerry Mcnerney"] <- "Jerry McNerney"
full_117_names[full_117_names == "Mark James Desaulnier"] <- "Mark DeSaulnier"
full_117_names[full_117_names == "Karen Lorraine Jacqueline (Jackie) Speier"] <- "Jackie Speir"
full_117_names[full_117_names == "Rohit Khanna"] <- "Ro Khanna"
full_117_names[full_117_names == "Anna Georges Eshoo"] <- "Anna G. Eshoo"
full_117_names[full_117_names == "James Varni Panetta"] <- "Jimmy Panetta"
full_117_names[full_117_names == "Kevin Mccarthy"] <- "Kevin McCarthy"
full_117_names[full_117_names == "Adam Schiff"] <- "Adam B. Schiff"
full_117_names[full_117_names == "Tony Cárdenas"] <- "Tony Cardenas"
full_117_names[full_117_names == "Peter Rey Aguilar"] <- "Pete Aguilar"
full_117_names[full_117_names == "Grace Flores Napolitano"] <- "Grace F. Napolitano"
full_117_names[full_117_names == "Norma Judith Torres"] <- "Norma J. Torres"
full_117_names[full_117_names == "Linda Sánchez"] <- "Linda T. Sanchez"
full_117_names[full_117_names == "Nanette Diaz Barragán"] <- "Nanette Barragan"
full_117_names[full_117_names == "Jose Luis Correa"] <- "Lou Correa"
full_117_names[full_117_names == "Juan Vargas"] <- "Juan C. Vargas"
full_117_names[full_117_names == "Kamala Devi Harris"] <- "Kamala Harris"
full_117_names[full_117_names == "Diana Degette"] <- "Diana DeGette"
full_117_names[full_117_names == "Joseph Neguse"] <- "Joe Neguse"
full_117_names[full_117_names == "Kenneth Robert Buck"] <- "Ken Buck"
full_117_names[full_117_names == "John Wright Hickenlooper"] <- "John Hickenlooper"
full_117_names[full_117_names == "John Larson"] <- "John B. Larson"
full_117_names[full_117_names == "Rosa Delauro"] <- "Rosa DeLauro"
full_117_names[full_117_names == "James Himes"] <- "Jim Himes"
full_117_names[full_117_names == "Christopher Murphy"] <- "Christopher S. Murphy"
full_117_names[full_117_names == "Thomas Richard Carper"] <- "Thomas R. Carper"
full_117_names[full_117_names == "Christopher Coons"] <- "Chris Coons"
full_117_names[full_117_names == "Matthew L. Ii Gaetz"] <- "Matt Gaetz"
full_117_names[full_117_names == "Neal Patrick Dunn"] <- "Neal Dunn"
full_117_names[full_117_names == "John Henry Rutherford"] <- "John Rutherford"
full_117_names[full_117_names == "Alfred Jr. Lawson"] <- "Al Lawson"
full_117_names[full_117_names == "Darren Michael Soto"] <- "Darren Soto"
full_117_names[full_117_names == "Valdez Butler Demings"] <- "Val B. Demings"
full_117_names[full_117_names == "Charlie Joseph Jr. Crist"] <- "Charlie Crist"
full_117_names[full_117_names == "C. Scott Franklin"] <- "Scott Franklin"
full_117_names[full_117_names == "Vernon Buchanan"] <- "Vern Buchanan"
full_117_names[full_117_names == "William Steube"] <- "Greg Steube"
full_117_names[full_117_names == "Brian Jeffery Mast"] <- "Brian Mast"
full_117_names[full_117_names == "Alcee Lamar Hastings"] <- "Alcee L. Hastings"
full_117_names[full_117_names == "Theodore E. (Ted) Deutch"] <- "Ted Deutch"
full_117_names[full_117_names == "Frederica Wilson"] <- "Frederica S. Wilson"
full_117_names[full_117_names == "Richard Lynn (Rick) Scott"] <- "Rick Scott"
full_117_names[full_117_names == "Buddy Carter"] <- "Earl L. \"Buddy\" Carter"
full_117_names[full_117_names == "Jr. Bishop"] <- "Sanford D. Bishop Jr."
full_117_names[full_117_names == "Anderson Drew Iv Ferguson"] <- "Drew Ferguson"
full_117_names[full_117_names == "Lucy Mcbath"] <- "Lucy McBath"
full_117_names[full_117_names == "Jody Brownlow Hice"] <- "Jody B. Hice"
full_117_names[full_117_names == "Rick Allen"] <- "Rick W. Allen"
full_117_names[full_117_names == "Kaialiʻi Kahele"] <- "Kai Kahele"
full_117_names[full_117_names == "Brian Emanuel Schatz"] <- "Brian Schatz"
full_117_names[full_117_names == "Mazie Hirono"] <- "Mazie K. Hirono"
full_117_names[full_117_names == "Cynthia Axne"] <- "Cindy Axne"
full_117_names[full_117_names == "Charles Ernest Grassley"] <- "Charles E. Grassley"
full_117_names[full_117_names == "Russell Fulcher"] <- "Russ Fulcher"
full_117_names[full_117_names == "Michael Simpson"] <- "Mike Simpson"
full_117_names[full_117_names == "James Risch"] <- "Jim Risch"
full_117_names[full_117_names == "Michael Dean Crapo"] <- "Michael D. Crapo"
full_117_names[full_117_names == "Bobby Rush"] <- "Bobby L. Rush"
full_117_names[full_117_names == "Jesús García"] <- "Jesus \"Chuy\" Garcia"
full_117_names[full_117_names == "Danny Davis"] <- "Danny K. Davis"
full_117_names[full_117_names == "S. Raja Krishnamoorthi"] <- "Raja Krishnamoorthi"
full_117_names[full_117_names == "Janice Schakowsky"] <- "Jan Schakowsky"
full_117_names[full_117_names == "Darin Lahood"] <- "Darin LaHood"
full_117_names[full_117_names == "Richard Joseph Durbin"] <- "Richard J. Durbin"
full_117_names[full_117_names == "Frank Mrvan"] <- "Frank J. Mrvan"
full_117_names[full_117_names == "James Banks"] <- "Jim Banks"
full_117_names[full_117_names == "James Baird"] <- "Jim Baird"
full_117_names[full_117_names == "Gregory Pence"] <- "Greg Pence"
full_117_names[full_117_names == "André Carson"] <- "Andre Carson"
full_117_names[full_117_names == "Joseph Albert Iii Hollingsworth"] <- "Trey Hollingsworth"
full_117_names[full_117_names == "Michael Braun"] <- "Mike Braun"
full_117_names[full_117_names == "Jake Laturner"] <- "Jake LaTurner"
full_117_names[full_117_names == "Roger Wayne Marshall"] <- "Roger Marshall"
full_117_names[full_117_names == "James Comer"] <- "James R. Comer"
full_117_names[full_117_names == "Harold Dallas (Hal) Rogers"] <- "Harold Rogers"
full_117_names[full_117_names == "Garland H. (Andy) Iv Barr"] <- "Andy Barr"
full_117_names[full_117_names == "Addison Mitchell (Mitch) Mcconnel"] <- "Mitch McConnel"
full_117_names[full_117_names == "Cedric Richmond"] <- "Cedric L. Richmond"
full_117_names[full_117_names == "John Neely Kennedy"] <- "John Kennedy"
full_117_names[full_117_names == "Richard Edmund Neal"] <- "Richard E. Neal"
full_117_names[full_117_names == "James Mcgovern"] <- "Jim Mcgovern"
full_117_names[full_117_names == "Katherine Clark"] <- "Katherine M. Clark"
full_117_names[full_117_names == "Ayanna Pressley"] <- "Ayanna S. Pressley"
full_117_names[full_117_names == "Stephen Lynch"] <- "Stephen F. Lynch"
full_117_names[full_117_names == "Edward John Markey"] <- "Edward J. Markey"
full_117_names[full_117_names == "C. A. (Dutch) Ruppersberger"] <- "C.A. Dutch Ruppersberger"
full_117_names[full_117_names == "Anthony Gregory Brown"] <- "Anthony G. Brown"
full_117_names[full_117_names == "Steny Hamilton Hoyer"] <- "Steny H. Hoyer"
full_117_names[full_117_names == "Jamie Ben Raskin"] <- "Jamie Raskin"
full_117_names[full_117_names == "Benjamin Louis Cardin"] <- "Benjamin L. Cardin"
full_117_names[full_117_names == "Christopher Van Hollen"] <- "Chris Van Hollen"
full_117_names[full_117_names == "Jr. King"] <- "Angus King"
full_117_names[full_117_names == "Susan Margaret Collins"] <- "Susan Collins"
full_117_names[full_117_names == "John Bergman"] <- "Jack Bergman"
full_117_names[full_117_names == "Frederick Stephen Upton"] <- "Fred Upton"
full_117_names[full_117_names == "Lisa Mcclain"] <- "Lisa McClain"
full_117_names[full_117_names == "Deborah Ann Stabenow"] <- "Debbie Stabenow"
full_117_names[full_117_names == "Angela Craig"] <- "Angie Craig"
full_117_names[full_117_names == "Betty Mccollum"] <- "Betty McCollum"
full_117_names[full_117_names == "Thomas Earl Ii Emmer"] <- "Tom Emmer"
full_117_names[full_117_names == "Peter Stauber"] <- "Pete Stauber"
full_117_names[full_117_names == "Ii Cleaver"] <- "Emanuel Cleaver II"
full_117_names[full_117_names == "Samuel Graves"] <- "Sam Graves"
full_117_names[full_117_names == "Joshua David Hawley"] <- "Josh Hawley"
full_117_names[full_117_names == "Steven Palazzo"] <- "Steven M. Palazzo"
full_117_names[full_117_names == "Sr. Rosendale"] <- "Matt Rosendale"
full_117_names[full_117_names == "Jr. (G.k.) Butterfield"] <- "G.K. Butterfield"
full_117_names[full_117_names == "Deborah Ross"] <- "Deborah K. Ross"
full_117_names[full_117_names == "Gregory Francis Murphy"] <- "Greg Murphy"
full_117_names[full_117_names == "David Eugene Price"] <- "David E. Price"
full_117_names[full_117_names == "Virginia Ann Foxx"] <- "Virginia Foxx"
full_117_names[full_117_names == "Patrick Mchenry"] <- "Patrick T. McHenry"
full_117_names[full_117_names == "Theodore Paul Budd"] <- "Ted Budd"
full_117_names[full_117_names == "Thomas Roland (Thom) Tillis"] <- "Thom Tillis"
full_117_names[full_117_names == "Richard Burr"] <- "Richard M. Burr"
full_117_names[full_117_names == "Donald Bacon"] <- "Don Bacon"
full_117_names[full_117_names == "Debra (Deb) Fischer"] <- "Deb Fischer"
full_117_names[full_117_names == "Benjamin Eric Sasse"] <- "Ben Sasse"
full_117_names[full_117_names == "Ann Mclane Kuster"] <- "Ann McLane Kuster"
full_117_names[full_117_names == "Margaret (Maggie) Hassan"] <- "Maggie Hassan"
full_117_names[full_117_names == "Jefferson Van Drew"] <- "Jeff Van Drew"
full_117_names[full_117_names == "Christopher Henry Smith"] <- "Christopher H. Smith"
full_117_names[full_117_names == "Jr. Pallone"] <- "Frank Pallone Jr."
full_117_names[full_117_names == "Tomaz Malinowski"] <- "Tom Malinowski"
full_117_names[full_117_names == "Jr. Pascrell"] <- "Bill Pascrell Jr."
full_117_names[full_117_names == "Jr. Payne"] <- "Donald M. Payne Jr."
full_117_names[full_117_names == "Robert Menendez"] <- "Bob Menendez"
full_117_names[full_117_names == "Cory Anthony Booker"] <- "Cory Booker"
full_117_names[full_117_names == "Debra Haaland"] <- "Deb Haaland"
full_117_names[full_117_names == "Ben Ray Luján"] <- "Ben Ray Lujan"
full_117_names[full_117_names == "Alice (Dina) Titus"] <- "Dina Titus"
full_117_names[full_117_names == "Catherine Marie Cortez Masto"] <- "Catherine Cortez Masto"
full_117_names[full_117_names == "Jacklyn Sheryl Rosen"] <- "Jacky Rosen"
full_117_names[full_117_names == "Thomas Suozzi"] <- "Tom Suozzi"
full_117_names[full_117_names == "Kathleen Maura Rice"] <- "Kathleen Rice"
full_117_names[full_117_names == "Gregory Meeks"] <- "Gregory W. Meeks"
full_117_names[full_117_names == "Nydia Velázquez"] <- "Nydia M. Velazquez"
full_117_names[full_117_names == "Yvette Diane Clarke"] <- "Yvette D. Clarke"
full_117_names[full_117_names == "Jerrold Lewis Nadler"] <- "Jerrold Nadler"
full_117_names[full_117_names == "Carolyn Bosher Maloney"] <- "Carolyn B. Maloney"
full_117_names[full_117_names == "Thomas W. Ii Reed"] <- "Tom Reed"
full_117_names[full_117_names == "Joseph Morelle"] <- "Joseph D. Morelle"
full_117_names[full_117_names == "Charles Ellis (Chuck) Schumer"] <- "Charles E. Schumer"
full_117_names[full_117_names == "Robert Latta"] <- "Bob Latta"
full_117_names[full_117_names == "Marcia Carolyn (Marcy) Kaptur"] <- "Marcy Kaptur"
full_117_names[full_117_names == "Michael Turner"] <- "Michael R. Turner"
full_117_names[full_117_names == "Marcia Fudge"] <- "Marcia L. Fudge"
full_117_names[full_117_names == "Timothy Ryan"] <- "Tim Ryan"
full_117_names[full_117_names == "Robert Jones (Rob) Portman"] <- "Rob Portman"
full_117_names[full_117_names == "Frank Lucas"] <- "Frank D. Lucas"
full_117_names[full_117_names == "James Mountain Inhofe"] <- "James M. Inhofe"
full_117_names[full_117_names == "Peter Anthony Defazio"] <- "Peter A. DeFazio"
full_117_names[full_117_names == "Ronald Lee Wyden"] <- "Ron Wyden"
full_117_names[full_117_names == "Brendan Francis Boyle"] <- "Brendan F. Boyle"
full_117_names[full_117_names == "Christina Houlahan"] <- "Chrissy Houlahan"
full_117_names[full_117_names == "Lloyd Smucker"] <- "Lloyd K. Smucker"
full_117_names[full_117_names == "Glenn Thompson"] <- "Glenn \"GT\" Thompson"
full_117_names[full_117_names == "Michael Doyle"] <- "Mike Doyle"
full_117_names[full_117_names == "Patrick Joseph Toomey"] <- "Patrick J. Toomey"
full_117_names[full_117_names == "Jr. Casey"] <- "Bob Casey"
full_117_names[full_117_names == "James Langevin"] <- "Jim Langevin"
full_117_names[full_117_names == "John F. (Jack) Reed"] <- "Jack Reed"
full_117_names[full_117_names == "Addison Graves (Joe) Wilson"] <- "Joe Wilson"
full_117_names[full_117_names == "William Timmons"] <- "William R. Timmons IV"
full_117_names[full_117_names == "James Enos Clyburn"] <- "James E. Clyburn"
full_117_names[full_117_names == "Dustin Johnson"] <- "Dusty Johnson"
full_117_names[full_117_names == "Marion Michael (Mike) Rounds"] <- "Mike Rounds"
full_117_names[full_117_names == "Timothy Burchett"] <- "Tim Burchett"
full_117_names[full_117_names == "Scott Desjarlais"] <- "Scott DesJarlais"
full_117_names[full_117_names == "James Hayes Shofner Cooper"] <- "Jim Cooper"
full_117_names[full_117_names == "John Rose"] <- "John W. Rose"
full_117_names[full_117_names == "Mark Green"] <- "Mark E. Green"
full_117_names[full_117_names == "Stephen Cohen"] <- "Steve Cohen"
full_117_names[full_117_names == "William Francis (Bill) Hagerty"] <- "Bill Hagerty"
full_117_names[full_117_names == "Nicholas Taylor"] <- "Van Taylor"
full_117_names[full_117_names == "Elizabeth Fletcher"] <- "Lizzie Fletcher"
full_117_names[full_117_names == "Kevin Patrick Brady"] <- "Kevin Brady"
full_117_names[full_117_names == "Michael Mccaul"] <- "Michael McCaul"
full_117_names[full_117_names == "Vicente Jr. Gonzalez"] <- "Vicente Gonzalez"
full_117_names[full_117_names == "Jodey Cook Arrington"] <- "Jodey C. Arrington"
full_117_names[full_117_names == "Charles Roy"] <- "Chip Roy"
full_117_names[full_117_names == "Michael Burgess"] <- "Michael C. Burgess"
full_117_names[full_117_names == "Sylvia Garcia"] <- "Sylvia R. Garcia"
full_117_names[full_117_names == "Ii Doggett"] <- "Lloyd Doggett"
full_117_names[full_117_names == "Rafael Edward (Ted) Cruz"] <- "Ted Cruz"
full_117_names[full_117_names == "Blake Moore"] <- "Blake D. Moore"
full_117_names[full_117_names == "Willard Mitt (Mitt) Romney"] <- "Mitt Romney"
full_117_names[full_117_names == "Robert Wittman"] <- "Rob Wittman"
full_117_names[full_117_names == "Robert Scott"] <- "Robert C. Scott"
full_117_names[full_117_names == "Aston Donald Mceachin"] <- "A. Donald Mceachin"
full_117_names[full_117_names == "Benjamin Cline"] <- "Ben Cline"
full_117_names[full_117_names == "Donald Sternoff Jr. Beyer"] <- "Donald S. Beyer Jr."
full_117_names[full_117_names == "H. Morgan Griffith"] <- "Morgan Griffith"
full_117_names[full_117_names == "Gerald E. (Gerry) Connolly"] <- "Gerald E. Connolly"
full_117_names[full_117_names == "Timothy Michael (Tim) Kaine"] <- "Tim Kaine"
full_117_names[full_117_names == "Patrick Joseph Leahy"] <- "Patrick J. Leahy"
full_117_names[full_117_names == "Bernard Sanders"] <- "Bernie Sanders"
full_117_names[full_117_names == "Suzan Delbene"] <- "Suzan DelBene"
full_117_names[full_117_names == "Richard Ray (Rick) Larsen"] <- "Rick Larsen"
full_117_names[full_117_names == "Daniel Milton Newhouse"] <- "Dan Newhouse"
full_117_names[full_117_names == "Cathy Mcmorris Rodgers"] <- "Cathy McMorris Rodgers"
full_117_names[full_117_names == "Gwendolynne S. (Gwen) Moore"] <- "Gwen Moore"
full_117_names[full_117_names == "Thomas Tiffany"] <- "Tom Tiffany"
full_117_names[full_117_names == "Michael Gallagher"] <- "Mike Gallagher"
full_117_names[full_117_names == "David Mckinley"] <- "David B. Mckinley"
full_117_names[full_117_names == "Alex Mooney"] <- "Alex X. Mooney"
full_117_names[full_117_names == "Tom O'halleran"] <- "Tom O'Halleran"
full_117_names[full_117_names == "Jackie Speir"] <- "Jackie Speier"
full_117_names[full_117_names == "Jim Mcgovern"] <- "Jim McGovern"
full_117_names[full_117_names == "A. Donald Mceachin"] <- "A. Donald McEachin"
full_117_names[full_117_names == "David B. Mckinley"] <- "David B. McKinley"
full_117_names[full_117_names == "Addison Mitchell (Mitch) Mcconnell"] <- "Mitch McConnell"
```


# Merge 117th Relgion and DW nominate
```{r}
#initial merge so we can see which ones are mismatched
hopes_and_prayers <- rel_117 %>% 
  full_join(full_117_names, rel_117, by = "name")

#still some issues so heading back!

#there are 567 observations so lets remove the ones without religion!
#YAYAYYAY now we have only 531 slayyyy
hopes <- hopes_and_prayers %>%
  drop_na(fix_relig)
```

# Now we want to build weighted ties
```{r}
hopes <- hopes %>% 
  select(name, nominate_dim1) 

#making an i and j 
hopes_117 <- hopes %>% 
  mutate(name_i =name) %>% 
  rename(name_j = name) %>% 
  mutate(dw_i = nominate_dim1) %>% 
  rename(dw_j = nominate_dim1)

#creating all the possible combinations
#but it fucking stupidly gets rid of the scores
combos_117 <- hopes_117 |>
  expand(name_i, name_j) |>
  filter(name_i != name_j) 

#merge back in scores goddamn
combos_of_117_start <- combos_117 %>% 
  right_join(hopes_117, by = c("name_i" = "name_j"))%>% 
  select(name_i, name_j, dw_i)

#merge dw of j
combos_dw_117 <- combos_of_117_start %>% 
  right_join(hopes_117, by = c("name_j" = "name_j")) 

#select the correct ones
combos_dw_117 <- combos_dw_117 %>% 
  select(name_i.x, name_j, dw_i.x, dw_j) %>% 
  rename(name_i =name_i.x,
         dw_i = dw_i.x)

#gut check make sure it doesnt lose any rows! yay!
yay_117 <- combos_dw_117 %>% 
  drop_na(dw_i, dw_j)

#yayyyy 
#now we have all of the combinations
```

# Create Similarity Score

```{r}
#check absolute value -- if the absolute value is the same then it is positive if not its negative, then if both negative ect

#this checks if one is negative or positive
yay_117 <- yay_117 %>% 
  mutate(pn_i = ifelse(abs(dw_i) == dw_i, "Positive", "Negative"),
         pn_j = ifelse(abs(dw_j) == dw_j, "Positive", "Negative"))

#now if they are both positive then subtract and find the absolute value 
yay <- yay_117 %>% 
  mutate(similarity = ifelse(pn_i == "Positive" & pn_j == "Positive", abs(dw_i - dw_j), 0),
         similarity = ifelse(pn_i == "Negative" & pn_j == "Negative", abs(abs(dw_i) - abs(dw_j)), similarity),
         similarity = ifelse(pn_i == "Positive" & pn_j == "Negative", abs(dw_i + abs(dw_j)), similarity),
         similarity = ifelse(pn_i == "Negative" & pn_j == "Positive", abs(abs(dw_i) + dw_j), similarity))
#YYYAYAYAYAY created it!! hot hot hot 
```



# Creating Similarity Score
```{r}
yay <- yay %>% 
  select(name_i, name_j, similarity)


#turn edge list into matrix
el_112 =as.matrix(sim_combos)

#turn into graph object
g_112=graph.data.frame(sim_combos)

#get adjacency matrix
d_112 = get.adjacency(g_112,sparse=FALSE) 
 
#changing it so all of them are zeros


```




