---
title: "religion"
author: "Naomi Liftman"
date: "2023-04-26"
output: pdf_document
---
# load packages
```{r messgae = FALSE, warning = FALSE, error = FALSE}
library(rio)
library(tidyverse)
library(ggplot2)
library(gdata)
library(smnet)
library(network)
library(igraph)
```

# 112th religion
```{r}
#importing the df 
religion_112 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/112congress.xlsx") 

#rename the last five names
relig_112 <- religion_112 %>% 
  rename_with(~ tolower(gsub(".", "", .x, fixed = TRUE))) %>% 
  rename("member_name" = 2) %>% 
  rename("religious_affiliation" = 4 ) %>% 
  select("member_name", "religious_affiliation", "party")

#now need to add the senate! 
religion_112_senate <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/112congress_senators.xlsx")

#rename the ones we are gonna use
relig_112_sen <- religion_112_senate %>% 
  rename("member_name" = 2) %>% 
  rename("religious_affiliation" = 3,
         "party" = 4) %>% 
  select("member_name", "religious_affiliation", "party")

#now making just one religion 
relig_112_all <- rbind(relig_112_sen, relig_112) %>% 
  drop_na(religious_affiliation)

#how many religions origionally
relig_112_all %>% 
  group_by(religious_affiliation) %>% 
  summarize(n = n())

rel_112 <- relig_112_all

#fix all other
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Quaker', 'Other', rel_112$religious_affiliation)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Nazarene', 'Other', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Greek Orthodox', 'Other', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Mormon', 'Other', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Buddhist', 'Other', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Muslim', 'Other', rel_112$fix_relig)

#fixing all catholic
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Anglican', 'Catholic', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Anglican Catholic', 'Catholic', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Roman Catholic', 'Catholic', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Unitarian', 'Catholic', rel_112$fix_relig)

#fixing all protestant
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'African Methodist Episcopal', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Evangelical Methodist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'United Methodist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Methodist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Christian', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Christian non-denominational', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Christian Reformed', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Christian Scientist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Church of Christ', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Antioch Orthodox Christian Church', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Eastern Orthodox', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Evangelical Christian', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Southern Baptist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Baptist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Episcopalian', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Presbyterian', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Lutheran', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Lutheran - Missouri Synod', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Evangelical Lutheran', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Seventh-day Adventist', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Community of Christ', 'Protestant', rel_112$fix_relig)
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Congregationalist Baptist', 'Protestant', rel_112$fix_relig)

rel_112[rel_112 == "Christian Reformed Church"] <- "Protestant"
rel_112[rel_112 == "Church of God"] <- "Protestant"
rel_112[rel_112 == "Congregationalist"] <- "Protestant"


#replace all NAs with unknown
rel_112$fix_relig <- ifelse(rel_112$religious_affiliation == 'Unspecified', 'Unknown', rel_112$fix_relig)
rel_112$fix_relig <- rel_112$fix_relig %>% replace_na('Unknown')

#how many different religions there are now!
rel_112 %>% 
  group_by(fix_relig) %>% 
  summarize(n = n())

#remove NAs
rel_112 <- rel_112 %>% 
  select("member_name", "fix_relig", "party") %>%
  drop_na(member_name)
```


# 117th religion
```{r}
#importing the df 
religion_117 <- import("/Users/naomiliftman/Desktop/GOV338/Final Project/117congress.xlsx")

#rename the last five names
relig_117 <- religion_117 %>% 
    rename_with(~ tolower(gsub(".", "", .x, fixed = TRUE))) %>%
  rename("type" = 2) %>% 
  rename("name" = 3) %>% 
  rename("party" = 4 ) %>% 
  rename("cont" = 5) %>% 
  rename("religion" = 6)

#rename the state
names(relig_117)[1] = "state"  

#remove the first row
relig_117 <- relig_117[-c(1:1), ]

#only want their name, relig, and party
relig_117 <- relig_117 %>% 
  select("name", "religion", "party")

#having a look at the origional breakdowns
relig_117 %>% 
  group_by(religion) %>% 
  summarize(n = n())

#creating a new 117
rel_117 <- relig_117 %>% 
  drop_na(name)

pp <- rel_117 %>% 
  group_by(religion) %>% 
  summarize(n = n())

#fix all protestant:
rel_117$fix_relig <- ifelse(rel_117$religion == 'Adventist', 'Protestant', rel_117$religion)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Baptist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Congregationalist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Episcopalian', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Lutheran', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Methodist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Pentecostal', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Pietist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Presbyterian', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Protestant unspecified', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Reformed', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Restorationist', 'Protestant', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Unitarian Universalist', 'Protestant', rel_117$fix_relig)

#fix all general catholic
rel_117$fix_relig <- ifelse(rel_117$religion == 'Orthodox', 'Catholic', rel_117$fix_relig)

#fixing all other
rel_117$fix_relig <- ifelse(rel_117$religion == 'Unaffiliated', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Buddhist', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Hindu', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Mormon', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Muslim', 'Other', rel_117$fix_relig)
rel_117$fix_relig <- ifelse(rel_117$religion == 'Nondenominational', 'Other', rel_117$fix_relig)

#replacing all of the NAs with Unknown along with the dont know
rel_117$fix_relig <- ifelse(rel_117$religion == 'Don\'t know/refused', 'Unknown', rel_117$fix_relig)
rel_117$fix_relig <- rel_117$fix_relig %>% replace_na('Unknown')

rel_117 %>% 
  group_by(fix_relig) %>% 
  summarize(n = n())

rel_117 <- rel_117 %>% 
  select("name", "fix_relig", "party") %>% 
  drop_na("name")
```

# Building a grouped df for count
```{r}
#building a full dataset 
rel_112 <- rel_112 %>% 
  mutate(session = "112th") %>% 
  rename(name = member_name)

rel_117 <- rel_117 %>% 
  mutate(session = "117th") 

full <- rbind(rel_112, rel_117) %>% 
  mutate(party = ifelse(party == "I", "D", party))
  
```

```{r}
library(nycflights13)
data(flights)
library(forcats)
```

```{r}
ggplot(data = full, aes(x = fix_relig, fill = party)) + 
  geom_bar(position = position_dodge(preserve = "single")) + 
  facet_wrap(~session) + 
  labs(title = "Religious Distribution of the 112th and 117th Congressional Sessions", fill = "Party") +
  xlab("Religion") +
  ylab("Count") + 
  scale_fill_manual(values = c("#C61C1C", "#1A36B8")) + 
  theme_linedraw()
```

# build grouped data frame for percents!
```{r}
#build easy dataset for 112
r <- rel_112 %>% 
  mutate(party = ifelse(party == 'I', "D", party)) %>% 
  group_by(fix_relig, party) %>% 
  summarize(count = n())

#built easy dataset for 117
d <- rel_117 %>% 
  mutate(party = ifelse(party == 'I', "D", party)) %>% 
  group_by(fix_relig, party) %>% 
  summarize(count = n())


r <- r %>% 
  mutate(session = "112th") %>% 
  mutate(percent = count/531)

d <- d %>% 
  mutate(session = "117th") %>% 
  mutate(percent = count/535)

full_perc <- rbind(r, d )

full_perc <- full_perc %>% 
  mutate(perc = percent*100)

```

# build percent graph!! she shall be sexy 
```{r}
ggplot(data = full_perc, aes(x = fix_relig, y= perc, fill = party)) + 
  geom_col(position = position_dodge(preserve = "single")) + 
  facet_wrap(~session) + 
  labs(title = "Religious Distribution of the 112th and 117th Congressional Sessions", fill = "Party") +
  xlab("Religion") +
  ylab("Percent") + 
  scale_fill_manual(values = c("#C61C1C", "#1A36B8")) + 
  theme_linedraw()
```

# 112th Build SEPERATE RELIGIONS MATRICES
#CATHOLICS
```{r}
#make matrix of religions
#making a number correlation for each lmao
re_112 <- rel_112 %>% 
  mutate(fix_relig = ifelse(rel_112$fix_relig == "Catholic", 1, fix_relig),
         fix_relig = ifelse(rel_112$fix_relig == "Jewish", 2, fix_relig),
         fix_relig = ifelse(rel_112$fix_relig == "Other", 3, fix_relig),
         fix_relig = ifelse(rel_112$fix_relig == "Protestant", 4, fix_relig),
         fix_relig = ifelse(rel_112$fix_relig == "Unknown", 5, fix_relig))  

#making an i and j 
re_112 <- re_112 %>% 
  mutate(member_i=member_name) %>% 
  rename(member_j = member_name) %>% 
  mutate(religion_i = fix_relig) %>% 
  rename(religion_j = fix_relig)

#creating all the possible combinations
combos <- re_112 |>
  expand(member_i, member_j) |>
  filter(member_i != member_j) 

#merge back in religion
combos_rel <- combos %>% 
  right_join(re_112, by = c("member_i" = "member_i")) %>% 
  select(member_i, member_j.x, religion_i)

#merge religion of j
combos_rel <- combos_rel %>% 
  right_join(re_112, by = c("member_j.x" = "member_j")) 

#select the correct ones
combos_112 <- combos_rel %>% 
  select(member_i.x, member_j.x, religion_i.x, religion_j) %>% 
  rename(member_i =member_i.x,
         member_j = member_j.x,
         religion_i = religion_i.x)

#create similarity score
combos_112 <- combos_112 %>% 
  mutate(similarity = ifelse(religion_i == 1 & religion_j == 1, 1, 0 )) %>% 
  select(-religion_i, -religion_j)

#now we only want to include the ones that include the same? 
sim_combos <-combos_112[!combos_112$similarity==0 ,]


#turn edge list into matrix
el_112 =as.matrix(combos_112)

#turn into graph object
g_112=graph.data.frame(sim_combos)

#get adjacency matrix
d_112 = get.adjacency(g_112,sparse=FALSE) 
 
#changing it so all of them are zeros


#export it for easier work!
write.csv(d_112, "religion_112.csv", row.names=FALSE)
```

```{r}
#make matrix of religions
#making a number correlation for each lmao
re_117 <- rel_117 %>% 
  mutate(fix_relig = ifelse(rel_117$fix_relig == "Catholic", 1, fix_relig),
         fix_relig = ifelse(rel_117$fix_relig == "Jewish", 2, fix_relig),
         fix_relig = ifelse(rel_117$fix_relig == "Other", 3, fix_relig),
         fix_relig = ifelse(rel_117$fix_relig == "Protestant", 4, fix_relig),
         fix_relig = ifelse(rel_117$fix_relig == "Unknown", 5, fix_relig))  

#making an i and j 
re_117 <- re_117 %>% 
  mutate(member_i = name) %>% 
  rename(member_j = name ) %>% 
  mutate(religion_i = fix_relig) %>% 
  rename(religion_j = fix_relig)

#creating all the possible combinations
combos_117 <- re_117 |>
  expand(member_i, member_j) |>
  filter(member_i != member_j) 

#merge back in religion
combos_rel_117 <- combos_117 %>% 
  right_join(re_117, by = c("member_i" = "member_i")) %>% 
  select(member_i, member_j.x, religion_i)

#merge religion of j
combos_rel_117 <- combos_rel_117 %>% 
  right_join(re_117, by = c("member_j.x" = "member_j")) 

#select the correct ones
combos_117_part_two_electric_boogaloo <- combos_rel_117 %>% 
  select(member_i.x, member_j.x, religion_i.x, religion_j) %>% 
  rename(member_i =member_i.x,
         member_j = member_j.x,
         religion_i = religion_i.x)

#create similarity score
combos_117_part_two_electric_boogaloo <- combos_117_part_two_electric_boogaloo %>% 
  mutate(similarity = ifelse(religion_i == 1 & religion_j == 1, 1, 0 )) %>% 
  select(-religion_i, -religion_j)

#now we only want to include the ones that include the same? 
sim_combos_117 <-combos_117_part_two_electric_boogaloo[!combos_117_part_two_electric_boogaloo$similarity==0 ,]

#turn into graph object
g_117=graph.data.frame(sim_combos_117)

#get adjacency matrix
d_117 = get.adjacency(g_117,sparse=FALSE) 

#export it for easier work!
write.csv(d_117, "matrix_religion_117.csv", row.names=FALSE)
```







