---
title: "pretty tables"
author: "Naomi Liftman"
date: "2023-05-02"
output: pdf_document
---
# Load Packages
```{r}
library(tidyverse)
library(gt)
library(gtExtras)
```


```{r}
# making a df!
variable_117 <- NA
estimate_117 <- NA
mean_117 <- NA
standard_error_117 <- NA
p_value_117 <- NA
model_number_117 <- NA
session_117 <- NA

# making a df!
variable_112 <- NA
estimate_112 <- NA
mean_112 <- NA
standard_error_112 <- NA
p_value_112 <- NA
model_number_112 <- NA
session_112 <- NA

m1_2 <- data.frame(variable_117, estimate_117, mean_117, standard_error_117, p_value_117, model_number_117, session_117)
#all first model of 117th
m1_2[1, ] <- list("Intercept", "0.9773", "3.0531", "0.0088", "-", 1, 117)
m1_2[nrow(m1_2) + 1, ] <- list("Religion", "-0.0942", "-0.2045", "0.0032", "~0.00", 1, 117)
m1_2[nrow(m1_2) + 1, ] <- list("Party", "-2.2986", "-0.1447", "0.0076", "~0.00", 1, 117)
m1_2[nrow(m1_2) + 1, ] <- list("Ideology", "0.5295", "-0.2823", "0.0096", "~0.00", 1, 117)

m1_3 <- data.frame(variable_112, estimate_112, mean_112, standard_error_112, p_value_112, model_number_112, session_112)
#all first model of 112th
m1_3[1, ] <- list("Intercept", "0.0026", "0.1798", "0.0008", "-", 1, 112)
m1_3[nrow(m1_3) + 1, ] <- list("Religion", "0.0262", "0.0003", "0.0011", "0.53", 1, 112)
m1_3[nrow(m1_3) + 1, ] <- list("Party", "0.0012", "-0.0282", "0.0007", "0.38", 1, 112)
m1_3[nrow(m1_3) + 1, ] <- list("Ideology", "0.0003", "0.1716", "0.0009", "0.37", 1, 112)

m1_2 <- m1_2 %>% 
  select(estimate_117:p_value_117)

m1_3 <- m1_3 %>% 
  select(variable_112:p_value_112)

total_m1 <- cbind(m1_2, m1_3)


model_1_2 <- gt(total_m1)

model_1_2 <- model_1_2 %>% 
  tab_options(
    footnotes.marks = "*"
  ) %>% 
  cols_move_to_start(
    columns = c(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)) %>% 
  tab_spanner(
    label = "112th Congress",
    columns = c(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)
  ) |>
  tab_spanner(
    label = "117th Congress",
    columns = c(estimate_117, mean_117, standard_error_117, p_value_117)
  ) %>% 
  cols_label(
    variable_112 = "",
    estimate_112 = "Estimate",
    mean_112 = "Mean",
    standard_error_112 = "St. Error",
    p_value_112 = "p-value",
    estimate_117 = "Estimate",
    mean_117 = "Mean",
    standard_error_117 = "St. Error",
    p_value_117 = "p-value",
  ) %>% 
  gt_add_divider(columns = "p_value_112") %>% 
  tab_footnote(
    footnote = "p < .05",
    locations = cells_body(
      columns = c(p_value_117), rows = 2:4) 
  ) %>% 
  cols_align(
  align = c("right"),
  columns = everything()
)

  
model_1_2

```









```{r}
# making a df for 112
variable_112 <- NA
estimate_112 <- NA
mean_112 <- NA
standard_error_112 <- NA
p_value_112 <- NA

# making a df for 112
variable_117 <- NA
estimate_117 <- NA
mean_117 <- NA
standard_error_117 <- NA
p_value_117 <- NA

m2_1 <- data.frame(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)

m2_2 <- data.frame(variable_117, estimate_117, mean_117, standard_error_117, p_value_117)

#adding second model for 112th
m2_1[1, ] <- list("Intercept", "0.1140", "95.6599", "0.0007", "-")
m2_1[nrow(m2_1) + 1, ] <- list("Catholic", "-0.0026", "0.0632", "0.0021", "0.77")
m2_1[nrow(m2_1) + 1, ] <- list("Jewish", "-0.0161", "0.0079", "0.0082", "0.48")
m2_1[nrow(m2_1) + 1, ] <- list("Other", "0.0345", "0.0642", "0.0134", "0.32")
m2_1[nrow(m2_1) + 1, ] <- list("Protestant", "-0.0041", "-0.4574", "0.0012", "0.74")
m2_1[nrow(m2_1) + 1, ] <- list("Unknown", "0.0859", "0.2463", "0.0576", "0.23")

#adding second model for 117th
m2_2[1, ] <- list("Intercept", "0.1286", "108.6771", "0.0008", "-")
m2_2[nrow(m2_2) + 1, ] <- list("Catholic", "0.0011", "-0.3986", "0.0021", "0.90")
m2_2[nrow(m2_2) + 1, ] <- list("Jewish", "-0.0111", "-0.0409", "0.0102", "0.62")
m2_2[nrow(m2_2) + 1, ] <- list("Other", "0.0173", "-0.0165", "0.0113", "0.54")
m2_2[nrow(m2_2) + 1, ] <- list("Protestant", "-0.0052", "-0.0708", "0.0014", "0.43")
m2_2[nrow(m2_2) + 1, ] <- list("Unknown", "0.0217", "0.0774", "0.0190", "0.48")
```

# MODEL 2 TABLE

```{r}
m2_2 <- m2_2 %>% 
  select(estimate_117:p_value_117)
total_m1 <- cbind(m2_1, m2_2)

model_2 <- gt(total_m1)

model_2 <- model_2 %>% 
  tab_options(
    footnotes.marks = "*"
  ) %>% 
  tab_spanner(
    label = "112th Congress",
    columns = c(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)
  ) |>
  tab_spanner(
    label = "117th Congress",
    columns = c(estimate_117, mean_117, standard_error_117, p_value_117)
  ) %>% 
  cols_label(
    variable_112 = "",
    estimate_112 = "Estimate",
    mean_112 = "Mean",
    standard_error_112 = "St. Error",
    p_value_112 = "p-value",
    estimate_117 = "Estimate",
    mean_117 = "Mean",
    standard_error_117 = "St. Error",
    p_value_117 = "p-value",
  ) %>% 
  gt_add_divider(columns = "p_value_112") %>% 
  tab_footnote(
    footnote = "p < .05",
    locations = cells_body(
      columns = c(p_value_117), rows = 2:4) 
  ) %>% 
  cols_align(
  align = c("right"),
  columns = everything()
)

  
model_2
```













# MODEL 3 table
```{r}
# making a df for 112
variable_112 <- NA
estimate_112 <- NA
mean_112 <- NA
standard_error_112 <- NA
p_value_112 <- NA

# making a df for 112
variable_117 <- NA
estimate_117 <- NA
mean_117 <- NA
standard_error_117 <- NA
p_value_117 <- NA

m3_1 <- data.frame(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)

m3_2 <- data.frame(variable_117, estimate_117, mean_117, standard_error_117, p_value_117)

m3_1[1, ] <- list("Intercept", "0.0025", "0.0056", "0.0032", "-")
m3_1[nrow(m3_1) + 1, ] <- list("Catholic", "0.0004", "-0.0120", "0.0021", "0.36")
m3_1[nrow(m3_1) + 1, ] <- list("Jewish", "-0.0008",  "0.0132", "0.0082", "0.59")
m3_1[nrow(m3_1) + 1, ] <- list("Other", "-0.0034", "-0.0010", "0.0134", "0.29")
m3_1[nrow(m3_1) + 1, ] <- list("Protestant", "0.0004", "0.0016", "0.0012", "0.22")
m3_1[nrow(m3_1) + 1, ] <- list("Unknown", "-0.0039",  "0.0013", "0.0576", "0.14")
m3_1[nrow(m3_1) + 1, ] <- list("Party", "0.0012", "-0.0001", "0.0027", "0.03")
m3_1[nrow(m3_1) + 1, ] <- list("Ideology", "0.0004", "-0.0077", "0.0036", "0.72")



m3_2[1, ] <- list("Intercept", "0.9466", "2.4205", "0.0088", "-")
m3_2[nrow(m3_2) + 1, ] <- list("Catholic", "0.0614", "-0.4138", "0.0054", "0.22")
m3_2[nrow(m3_2) + 1, ] <- list("Jewish", "0.3901", "-0.9262", "0.0256", "~0.00")
m3_2[nrow(m3_2) + 1, ] <- list("Other", "-0.0919", "0.6634", "0.0282", "0.54")
m3_2[nrow(m3_2) + 1, ] <- list("Protestant", "-0.1501", "0.0105", "0.0035", "~0.00")
m3_2[nrow(m3_2) + 1, ] <- list("Unknown", "0.3685", "-0.2788", "0.0475", "0.04")
m3_2[nrow(m3_2) + 1, ] <- list("Party", "0.3074", "-0.8091", "0.0076", "~0.00")
m3_2[nrow(m3_2) + 1, ] <- list("Ideology", "-0.7167", "-0.0624", "0.0096", "~0.00")
```


```{r}
m3_2 <- m3_2 %>% 
  select(estimate_117:p_value_117)

total_m1 <- cbind(m3_1, m3_2)

model_3 <- gt(total_m1)

model_3 <- model_3 %>% 
  tab_options(
    footnotes.marks = "*"
  ) %>% 
  tab_spanner(
    label = "112th Congress",
    columns = c(variable_112, estimate_112, mean_112, standard_error_112, p_value_112)
  ) |>
  tab_spanner(
    label = "117th Congress",
    columns = c(estimate_117, mean_117, standard_error_117, p_value_117)
  ) %>% 
  cols_label(
    variable_112 = "",
    estimate_112 = "Estimate",
    mean_112 = "Mean",
    standard_error_112 = "St. Error",
    p_value_112 = "p-value",
    estimate_117 = "Estimate",
    mean_117 = "Mean",
    standard_error_117 = "St. Error",
    p_value_117 = "p-value",
  ) %>% 
  gt_add_divider(columns = "p_value_112") %>% 
  tab_footnote(
    footnote = "p < .05",
    locations = cells_body(
      columns = c(p_value_117), rows = c(3, 5, 7, 8)) 
  ) %>% 
  tab_footnote(footnote = "p < .05",
    locations = cells_body(
      columns = c(p_value_112), rows = 7)) %>% 
  cols_align(
  align = c("right"),
  columns = everything()
)

  
model_3
```



